version: '3.8'

services:
  post-rest-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: app
    # If you want to reach it from your host:
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring
    depends_on:
      - post-rest-app  

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
       GF_SECURITY_ADMIN_USER: admin
       GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - monitoring
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      # Persist Grafana DB (users, starred dashboards, etc.)
      - grafana-data:/var/lib/grafana

volumes: 
  grafana-data:

networks:
  monitoring:
    driver: bridge
